ta404:
  application:
    name: bysj
    version: 5.1.1.RELEASE
  modules:
    captcha:
      // 是否启用验证码
#      user-check-code: false
#      # 验证码类型，可选值：simple/slide
#      check-code-type: simple
#      password-validation-error-number: 0
spring:
  profiles:
    active: dev,mybatis,token,deploy
  application:
    name: ${ta404.application.name}
  main:
    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 20MB
server:
  port: 8083
  servlet:
    session:
      timeout: 7200s
    context-path: /bysj
